#!/usr/bin/env bash
#installs nginx and redirects to holberton school string
sudo apt-get -y update
sudo apt-get -y install nginx
file=/var/www/html/index.html
file1=/etc/nginx/sites-available/default
sudo bash -c "echo 'Hello World!' > $file"
service nginx start
phrase="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "30i $phrase" $file1
sudo service nginx restart
