#!/usr/bin/bash
#install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "9i ENABLED=1" /etc/default/haproxy
cat >> /etc/haproxy/haproxy.cfg <<EOF

defaults
    mode http
    balance roundrobin

frontend ayoub_fronend
    bind *:80
    mode http
    default_backend ayoub_backend

backend ayoub_backend
    server 395564-web-01 54.146.56.232:80 check
    server 395564-web-02 34.207.58.85:80 check

EOF
sudo service haproxy restart
