#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd
#only display username, user id and Home directory path for the user
while IFS=':' read -r name; do
    # Use 'echo' to print the extracted fields separated by ':' (username:user ID:home directory)
    echo "$name" | cut -d":" -f1,3,6
done < "/etc/passwd"
