#!/usr/bin/env bash
# This script that displays numbers from 1 to 20 and
# using while loop and case statement.
count=1
while [ $count -lt 21 ]
do
    echo $count
    case "$count" in
	4)  echo "bad luck from China"
	    ;;
	9) echo "bad luck from Japan"
	    ;;
	17) echo "bad luck from Italy"
	    ;;
	esac
    ((count++))
done
