#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements

facebook='8.8.8.8 facebook.com'
hosts=/etc/hosts
cp $hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "$facebook" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
