#!/usr/bin/env bash
# web debugging
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
